<p>Атай Камбаров win-1-21 <br> Лабораторная работа №2 </p>

In [1]:
import numpy as np

<p>1.1 Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5</p>

In [2]:
my_array = np.arange(0, 100, 5)
print(my_array)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


<p>2.1 Из полученного массива получить массив с кратными 10 числами</p>

In [3]:
my_array = my_array[::2]
print(my_array)

[ 0 10 20 30 40 50 60 70 80 90]


<p>3.1 Получить двумерный массив с двумя столбцами</p>

In [4]:
my_array = my_array.reshape(-1, 2)
print(my_array)

[[ 0 10]
 [20 30]
 [40 50]
 [60 70]
 [80 90]]


<p>4.1 Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5</p>

In [5]:
my_second_array = my_array - 5
print(my_second_array)

[[-5  5]
 [15 25]
 [35 45]
 [55 65]
 [75 85]]


<p>5.1 Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы</p>

In [6]:
result = np.hstack((my_array, my_second_array))
print(result)

[[ 0 10 -5  5]
 [20 30 15 25]
 [40 50 35 45]
 [60 70 55 65]
 [80 90 75 85]]


<p>7.1 Оставить только те значения, которые не изменились после деления</p>

In [8]:
unchanged_values = my_array[my_array == my_array_copy]
print(unchanged_values)

[ 0 10 60 70 80 90]


<p>8.1 Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки</p>

In [9]:
unchanged_values = unchanged_values.reshape(3, -1)
unchanged_values = unchanged_values[::-1]

print(unchanged_values)

[[80 90]
 [60 70]
 [ 0 10]]


<p>9.1 Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().</p>

In [10]:
for i in unchanged_values:
    print(f'Среднее для {i[0]} и {i[1]}: {np.mean(i)}')
    print(f'Медиана для {i[0]} и {i[1]}: {np.median(i)}')
    print(f'Стандартное отклонение для {i[0]} и {i[1]}: {np.std(i)}')

Среднее для 80 и 90: 85.0
Медиана для 80 и 90: 85.0
Стандартное отклонение для 80 и 90: 5.0
Среднее для 60 и 70: 65.0
Медиана для 60 и 70: 65.0
Стандартное отклонение для 60 и 70: 5.0
Среднее для 0 и 10: 5.0
Медиана для 0 и 10: 5.0
Стандартное отклонение для 0 и 10: 5.0


<p>10.1 Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.</p>

In [11]:
max_values = unchanged_values.max(axis=1)

normalized_array = unchanged_values / max_values[:, np.newaxis]
print(normalized_array)


[[0.88888889 1.        ]
 [0.85714286 1.        ]
 [0.         1.        ]]


<p>Использование команд библиотеки pandas</p>

<p>2.1 Импортируйте данные из файла “Global Population Trends(2016-2022).csv”.</p>

In [12]:
import pandas as pd
df = pd.read_csv('Global Population Trends(2016-2022).csv')
print(df)

          Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate

 <p>2.2  Считайте несколько первых записей таблицы (head())</p>

In [13]:
print(df.head())

       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           - 

 <p>2.3 Определите размерность данного фрейма (shape)</p>

In [14]:
print(df.shape)

(1073, 12)


 <p>2.4 Выведите название заголовков столбцов фрейма (columns)</p>

In [15]:
print(df.columns)

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


 <p>2.5 Получите описание всех переменных (полей) (info())</p>

In [16]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB
None


 <p>2.6 Удалите строки, не содержащие значения в столбце «Total Population» - “-”</p>

In [17]:
df = df[df['Total Population'] != '-']
print(df)

          Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate

 <p>2.7 Получите описательную статистику по переменным (например, max(), min(), describe())</p>

In [18]:
print('Max total population: ' + df['Total Population'].max())
print('Min total population: ' + df['Total Population'].min(), end='\n\n')

print(df.describe())

Max total population: 99,258
Min total population: 1,057,198

              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000


 <p>2.8 Выполните сортировку данных по нескольким критериям</p>

In [19]:
print(df.sort_values(by=['Birth Rate', 'Death Rate']))

            Country  Year Total Population Urban Population Rural Population  \
15   American Samoa  2018           48,424           42,203            6,221   
16   American Samoa  2019           47,321           41,239            6,082   
18   American Samoa  2021           45,035           39,257            5,778   
21          Andorra  2020           77,700           68,311            9,389   
22          Andorra  2021           79,034           69,438            9,596   
..              ...   ...              ...              ...              ...   
864         Somalia  2018       15,411,094        6,930,523        8,480,571   
694           Niger  2021       25,252,722        4,230,083       21,022,639   
693           Niger  2020       24,333,639        4,045,711       20,287,928   
692           Niger  2019       23,443,393        3,872,145       19,571,248   
691           Niger  2018       22,577,058        3,708,282       18,868,776   

    Population Density Life Expectancy 

 <p>2.9 Выведите название страны, которая имеет максимальную численность населения</p>

In [20]:
df['Total Population'] = df['Total Population'].str.replace(',', '')
df['Total Population'] = pd.to_numeric(df['Total Population'])
print(df.sort_values(by=['Total Population']).tail(1)['Country'])

205    China
Name: Country, dtype: object


 <p>2.10 Выведите название страны, которая имеет минимальную численность населения</p>

In [21]:
print(df.sort_values(by=['Total Population']).head(1)['Country'])

994    Tuvalu
Name: Country, dtype: object


 <p>2.11 Экспорт фрейма в MS Excel</p>

In [22]:
df.to_excel(r'C:\atay_works\bigData\lab2')